### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by MayeulC** [Guilhem74/RoboFrc#3]
@Guilhem74 You guys should put a license file ;)

You should probably pick MIT/BSD or GPL, discuss the choice with @Gnu-Bricoleur. Of course, you can also dual-license it at well!

Edit: Also ["Author: Mayeul"](https://github.com/Guilhem74/RoboFrc/blob/master/5553_2017/src/VictorSPRampe.h#L5) - LOL. I give you guys a copyright attribution for whatever I wrote in this old codebase. @JeanninM ?

**Comment by Guilhem74** [comment]
Thanks @MayeulC
